import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import Image from "next/image";

export default function Detail(props: any) {
  const { response } = props;
  const router = useRouter();
  console.log("response", response);

  return (
    <>
      <Head>
        <title>{response.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <Image
              src={response.thumbnail}
              alt={response.title}
              width={300}
              height={300}
              fetchPriority="low"
              sizes="50vw"
              loading="lazy"
            />
            <div>{response.title}</div>
            <div>{response.description}</div>
            <div>{response.price}</div>
            <div>{response.availabilityStatus}</div>
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async (context: any) => {
  const { id } = context.query;

  const options = {
    method: "GET",
  };
  const response = await fetch(`https://dummyjson.com/products/${id}`, options)
    .then((response) => response.json())
    .catch((err) => console.error(err));

  return {
    props: {
      response: JSON.parse(JSON.stringify(response)) || null,
    },
  };
};
